# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.27.0
from typing import Any, Optional

import pydantic


class Alert(pydantic.BaseModel):
    id: Any
    prompt_id: Any
    output_id: Any
    code_snippet: Any
    trigger_string: Any
    trigger_type: Any
    trigger_category: Optional[Any]
    timestamp: Any


class Output(pydantic.BaseModel):
    id: Any
    prompt_id: Any
    timestamp: Any
    output: Any


class Prompt(pydantic.BaseModel):
    id: Any
    timestamp: Any
    provider: Optional[Any]
    system_prompt: Optional[Any]
    user_prompt: Any
    type: Any


class Setting(pydantic.BaseModel):
    id: Any
    ip: Optional[Any]
    port: Optional[Any]
    llm_model: Optional[Any]
    system_prompt: Optional[Any]
    other_settings: Optional[Any]
