# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.27.0
import dataclasses
from typing import Any, Optional


@dataclasses.dataclass()
class Alert:
    id: Any
    prompt_id: Any
    output_id: Any
    code_snippet: Any
    trigger_string: Any
    trigger_type: Any
    trigger_category: Optional[Any]
    timestamp: Any


@dataclasses.dataclass()
class Output:
    id: Any
    prompt_id: Any
    timestamp: Any
    output: Any
    status: Any


@dataclasses.dataclass()
class Prompt:
    id: Any
    timestamp: Any
    provider: Optional[Any]
    system_prompt: Optional[Any]
    user_prompt: Any
    type: Any
    status: Any


@dataclasses.dataclass()
class Setting:
    id: Any
    ip: Optional[Any]
    port: Optional[Any]
    llm_model: Optional[Any]
    system_prompt: Optional[Any]
    other_settings: Optional[Any]
