# These set of workflows run on every pull request
name: Run - pull_request

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  security:
    name: Security Checks
    uses: ./.github/workflows/security.yml
  ci:
    name: Build, Test & Lint
    uses: ./.github/workflows/ci.yml
  image-build:
    name: OCI Image - Build
    needs: [ci] # No need to build the image if the CI fails
    uses: ./.github/workflows/image-build.yml
    with:
      artifact-name: "codegate-image"
  integration-tests:
    name: Integration Tests
    needs: [ci, image-build] # We need the image available in order to run the integration tests
    uses: ./.github/workflows/integration-tests.yml
    with:
      artifact-name: "codegate-image"
    secrets:
      copilot-key: ${{ secrets.INTEGRATION_TESTS_COPILOT_KEY }}
