# These set of workflows run on every published release
name: Run - release_published

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  image-publish:
    name: OCI Image - Publish
    uses: ./.github/workflows/image-publish.yml      
